# Generated by Django 5.0 on 2026-06-03 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_needed', models.IntegerField(default=1)),
                ('hospital_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
