# Generated by Django 5.0 on 2026-06-04 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_existing_requests(apps, schema_editor):
    """Delete all existing blood requests to prepare for location FK migration"""
    BloodRequest = apps.get_model('blood_requests', 'BloodRequest')
    BloodRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_existing_requests),
        migrations.RemoveIndex(
            model_name='bloodrequest',
            name='blood_reque_blood_g_1b92cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloodrequest',
            name='blood_reque_status_891e77_idx',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='division',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='upazila',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requests', to='locations.upazila'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group', 'status'], name='blood_reque_blood_g_401836_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['location'], name='blood_reque_locatio_2b55a8_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['requester'], name='blood_reque_request_408b0c_idx'),
        ),
    ]
