# Generated by Django 5.0 on 2026-06-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_d_name_744040_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.division')),
            ],
            options={
                'ordering': ['division', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upazilas', to='locations.district')),
            ],
            options={
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['division', 'name'], name='locations_d_divisio_d8165d_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['division'], name='locations_d_divisio_9011a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('division', 'name')},
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['district', 'name'], name='locations_u_distric_c3c908_idx'),
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['district'], name='locations_u_distric_e1074a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='upazila',
            unique_together={('district', 'name')},
        ),
    ]
