# Generated by Django 5.0 on 2026-06-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='donations_d_donatio_a63beb_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='donations_d_donor_i_b67ace_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['is_verified'], name='donations_d_is_veri_f46398_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['blood_request'], name='donations_d_blood_r_b832bc_idx'),
        ),
    ]
