# Generated by Django 5.0 on 2026-06-02 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='donations_d_donatio_a63beb_idx'),
        ),
    ]
